import { Dimensions, StyleSheet } from "react-native";

export const style = StyleSheet.create({
    container:{
        flex:1,
        alignContent:'center',
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:'#558DC2'
    },
    boxTop:{
        height:Dimensions.get('window').height/3,
        width:'100%',
        justifyContent:'center',
        alignItems:'center',
        //backgroundColor:'red'
    },
    boxMid:{
        height:Dimensions.get('window').height/4,
        width:'100%',
        paddingHorizontal:38
    },
    boxBottom:{
        height:Dimensions.get('window').height/3,
        width:'100%',
        alignItems:'center',
        paddingTop:50
    },
    logo:{
        width:300,
        height:125
    },
    textTitle:{
        fontFamily:'inter',
        color:'#d3d3d3',
        fontWeight:'bold',
        fontSize:20,
    },
    boxInput:{
        width:'100%',
        height:40,
        borderWidth:1,
        borderRadius:40,
        marginTop:10,
        marginBottom:10,
        flexDirection:'row',
        alignItems:'center',
        paddingHorizontal:5,
        backgroundColor:'#dcdcdc',
    },
    textInput:{
        height:'100%',
        width:'90%',
        paddingLeft:10,
        borderRadius:40,
        fontSize:20
    },
    button:{
        width:200,
        height:50,
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'#105494',
        borderRadius:40,
        shadowColor:'#000',
        shadowOffset:{
            width: 0,
            height: 3
        },
        shadowOpacity: 0.29,
        shadowRadius: 4.65,
        elevation: 7
    },
    textButton:{
        fontSize:20,
        fontWeight:'bold',
        color:'#d3d3d3'
    },
    textForget:{
        paddingLeft:8,
        fontSize:16,
        fontWeight:'bold',
        color:'#d3d3d3'
    },
    textBotton:{
        fontSize:16,
        fontWeight:'bold',
        color:'#d3d3d3'
    }
})